### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by ebiwonjumit**

### CODE REVIEW

**Comment by dragazo** [comment]
Just to make sure this doesn't affect the demo tonight, I've reverted this change and we can reopen the PR later.

**Comment by ebiwonjumit** [comment]
I just tested that change and it was good, it'll break my demo for tonight!

**Comment by dragazo** [comment]
Well I don't know if it'll break Will's demos, and it's extremely last-minute to be making any changes since everyone involved doesn't have time to test with the new version. I think you just need a different demo that doesn't use this extremely new feature.

**Comment by ebiwonjumit** [comment]
Understood, I can find a work around

**Pull request merged**
