### PR TITLE
Major Updates

### PR DESCRIPTION
**Pull request by ebiwonjumit**

### CODE REVIEW

**Comment by dragazo** [comment]
Can you fix the merge conflicts?

For future reference, we do squash commits for concise git history, but that means if you keep using the old branch after merging you'll get these conflicts (and the pr looks bigger than it is since commits are duplicated from the pre-squashed history). So basically after we merge this, you can delete your branch and make a new branch off of the updated master branch.

**Comment by ebiwonjumit** [comment]
@dragazo Understood! I will make sure to always branch off of master!

**Review by dragazo — APPROVED** [review]
I haven't tested it, but it looks good to me. We can go ahead and merge it if you're ready for release.

**Comment by ebiwonjumit** [comment]
@dragazo On my computer, everything works fine. But let me do a final check tonight and then we can release it first thing in the morning.

**Comment by ebiwonjumit** [comment]
@dragazo please go ahead and merge

**Pull request merged**
