### PR TITLE
updated localhost fetch function

### PR DESCRIPTION
**Pull request by samankittani**
the await fetch was returning an error which would stop the mjs file from loading at all. This pull request fixes that by handling the error gracefully.

### CODE REVIEW

**Comment by dragazo** [comment]
Actually if all you need to do is check if the extension was loaded from localhost, you could do something super short like `window.location.search.includes('localhost')`. It misses an edge case (non-dev this extension plus dev other extension), but actual users would never run into it, so it should be fine and a lot simpler.

**Comment by samankittani** [comment]
Very true, thanks! I went ahead and simplified it.

**Comment by dragazo** [comment]
The diff still shows the old version in two files (see files changed in this pr, or `git diff origin/master`). But the bug was already fixed either way, so I can go ahead and merge if you're ready.

**Comment by dragazo** [comment]
I'll go ahead and merge so the demos will be working

**Pull request merged**
