### PR TITLE
Dynamically loading Music App

### PR DESCRIPTION
**Pull request by ebiwonjumit**
I added in Devin's code and changed the Extension so that it now loads in Will's API Dynamically.

### CODE REVIEW

**Review by dragazo — APPROVED** [review]
Seems to be working fine, though I didn't test everything. I think it's a lot cleaner with this change, and it should auto-update with any (non-breaking) changes to Will's WebAudioAPI without having to update/bundle/publish/etc.

**Comment by dragazo** [comment]
Is this in a working form for publishing at this point? It seemed to be working last I checked, but a bunch has changed since then. It looks like some blocks have new slots, which will break existing projects. But if everyone's fine with that, we can merge the new version.

**Comment by ebiwonjumit** [comment]
Hello @dragazo mind if we hold off on merging till tomorrow! Still want to make sure all the new changes are working well!

**Comment by dragazo** [comment]
Sure, just let me know when it's ready for release

**Pull request merged**
